latemachine dates his exgirlfriend.

-- by enemy entropy

* introduction

after years of solitude,
latemachine spends his night in high blood pressure because exgirlfriend was vampir.

* background

blackhole is a thing which sucks, even the time.
since exgirlfriend's friend's boyfriend slapped again after an hour because it's okay!
boyfriend said it was an action of love:
it's normal behaviour.

after closing lights in kitchen,
enemy had seen on his way, this drama.
boyfriend was getting splooshed due to friend's tears.
in this sorrowful moment,
enemy enters into junky's birthday party.
baby was sleeping and latemachine was dancing with exgirlfriend while having a blackhole in basement.

* analysis

** boyfriend

after the discovery of static time in sydney university on 10/feb/2020,
boyfriend changed his hairstyle after einstein in 1910.
this phenomenon was magnificant.
but boyfriend got drunk and went macho.

** friend

friend stopped crying.
maybe she considers this behaviour normal now.

** latemachine

the word latemachine is a noun as well as adjective,
as like as a blackhole.
thus girlfriend is exgirlfriend.

** exgirlfriend

there exist 14 types of vampirs,
and exgirlfriend is latemachine's favorite.

* conclusion

the sun is coming out and latemachine must hurry.
